version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - intargovishtenet
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - "3306:3306"

  app:
    image: intargovishte
    container_name: intargovishte
    networks:
      - intargovishtenet
    build:
      context: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: ${MYSQL_DB}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}  # Ensure this is set
      DATABASE_URL: jdbc:mysql://mysql:3306/${MYSQL_DB}?createDatabaseIfNotExist=true
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  intargovishtenet:
    driver: bridge
