name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Docker Hub username or org
  REGISTRY: ytrufchev
  IMAGE_NAME: intargovishte

jobs:

  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login -u ${{ github.actor }} --password-stdin

    - name: Build and Publish
      run: |
        docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
